plugin: aws_ec2

aws_access_key: AKIA6CDE4F3UAKTTTDWA
aws_secret_key: 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

regions:
  - ap-south-1

filters:
  instance-state-name : running
 
keyed_groups:
  - key: tags.Name
    prefix: ""
    separator: ""

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address
