plugin: aws_ec2

aws_access_key: AKIA3OVJTVL5SD3KZQR7
aws_secret_key: 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

regions:
  - ap-southeast-1

filters:
  instance-state-name : running
 
keyed_groups:
  - key: tags.Name
    prefix: ""
    separator: ""

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address
